from enum import Enum

class Brand(str, Enum):
    cadillac = "Cadillac"
    volkswagen = "Volkswagen"
    hummer = "Hummer"
    subaru = "Subaru"
    mini = "MINI"
    saab = "Saab"
    audi = "Audi"
    rivian = "Rivian"
    genesis = "Genesis"
    acura = "Acura"
    land = "Land"
    maybach = "Maybach"
    volvo = "Volvo"
    honda = "Honda"
    saturn = "Saturn"
    mazda = "Mazda"
    plymouth = "Plymouth"
    lucid = "Lucid"
    mercedes_benz = "Mercedes-Benz"
    bmw = "BMW"
    maserati = "Maserati"
    smart = "smart"
    ferrari = "Ferrari"
    chevrolet = "Chevrolet"
    dodge = "Dodge"
    ford = "Ford"
    scion = "Scion"
    lexus = "Lexus"
    chrysler = "Chrysler"
    pontiac = "Pontiac"
    suzuki = "Suzuki"
    jeep = "Jeep"
    nissan = "Nissan"
    lincoln = "Lincoln"
    gmc = "GMC"
    toyota = "Toyota"
    lotus = "Lotus"
    mitsubishi = "Mitsubishi"
    karma = "Karma"
    mercury = "Mercury"
    polestar = "Polestar"
    hyundai = "Hyundai"
    fiat = "FIAT"
    jaguar = "Jaguar"
    rolls_royce = "Rolls-Royce"
    ram = "RAM"
    mclaren = "McLaren"
    lamborghini = "Lamborghini"
    alfa = "Alfa"
    kia = "Kia"
    bentley = "Bentley"
    buick = "Buick"
    infiniti = "INFINITI"
    bugatti = "Bugatti"
    tesla = "Tesla"
    aston = "Aston"
    porsche = "Porsche"

brand_list = (
    "Scion", "Saab", "Lexus", "Rivian", "MINI", "Alfa", "Land", "INFINITI", "Rolls-Royce",
    "Cadillac", "Nissan", "Toyota", "McLaren", "Ferrari", "Karma", "Hyundai", "Suzuki",
    "Chrysler", "Porsche", "Jaguar", "Kia", "Buick", "Bentley", "Tesla", "Ford", "Maserati",
    "Pontiac", "Subaru", "Polestar", "Jeep", "Mercedes-Benz", "Chevrolet", "Maybach",
    "Lamborghini", "smart", "Bugatti", "Plymouth", "Lucid", "Mercury", "Aston", "FIAT",
    "Genesis", "Mazda", "Mitsubishi", "Lincoln", "GMC", "Dodge", "Saturn", "Hummer",
    "BMW", "Audi", "Volvo", "Acura", "Volkswagen", "Lotus", "RAM", "Honda"
)
